language: cpp
compiler:
  - gcc
before_script:
  - cd ..
  - git clone https://github.com/zeehio/speech-tools.git speech_tools
  - cd speech_tools
  - git checkout
  - ./configure && make
  - cd ../festival
script:
  - ./configure && make
  - cd ..
  - wget http://www.festvox.org/packed/festival/latest/festlex_CMU.tar.gz
  - tar xzf festlex_CMU.tar.gz
  - wget http://www.festvox.org/packed/festival/latest/festlex_POSLEX.tar.gz
  - tar xzf festlex_POSLEX.tar.gz
  - wget http://www.festvox.org/packed/festival/latest/festvox_kallpc16k.tar.gz
  - tar xzf festvox_kallpc16k.tar.gz
  - wget http://www.festvox.org/packed/festival/latest/festvox_rablpc16k.tar.gz
  - tar xzf festvox_rablpc16k.tar.gz
  - wget http://www.festvox.org/packed/festival/latest/festlex_OALD.tar.gz
  - tar xzf festlex_OALD.tar.gz
  - wget http://www.festvox.org/packed/festival/latest/festvox_cmu_us_rms_cg.tar.gz
  - tar xzf festvox_cmu_us_rms_cg.tar.gz
  - wget http://www.festvox.org/packed/festival/latest/festvox_cmu_us_awb_cg.tar.gz
  - tar xzf festvox_cmu_us_awb_cg.tar.gz
  - wget http://www.festvox.org/packed/festival/latest/festvox_cmu_us_slt_arctic_hts.tar.gz
  - tar xzf festvox_cmu_us_slt_arctic_hts.tar.gz
  - cd festival
  - make test

env:
  global:
   # The next declaration is the encrypted COVERITY_SCAN_TOKEN, created
   #   via the "travis encrypt" command using the project repo's public key
   - secure: "M7yKdvVZ1GZor7aEfevjz7UEbbSN3VTmjZ8l94pqEqJibIXhx87vvnFR7fn3OO69QDUAyItMo6USolhG3G7kqZS3txODqtEJ7xx7aOua1dbrAJT5fgKHNosLwq/UnllwR3FSOFgJa9+9QNAsZvsg9+7b/gSSxrafV2AvjZUCmE8="

addons:
  coverity_scan:
    project:
      name: "zeehio/festival"
      description: "Your project description here"
    notification_email: sergioller@gmail.com
    build_command_prepend: ./configure
    build_command: make
    branch_pattern: coverity_scan

